# Generated by Django 4.1 on 2022-09-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioA', models.CharField(max_length=50)),
                ('usuarioB', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=500)),
                ('Leido', models.BooleanField(default=False)),
            ],
        ),
    ]
