# Generated by Django 4.1 on 2022-08-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('ambientes', models.IntegerField()),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('contacto_telefono', models.IntegerField()),
                ('contacto_email', models.EmailField(max_length=254)),
                ('precio', models.IntegerField()),
                ('fecha_de_alta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_descripcion', models.CharField(max_length=100)),
                ('motivo_ubicacion', models.CharField(max_length=100)),
                ('motivo_precio', models.IntegerField()),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('contacto_telefono', models.IntegerField()),
                ('contacto_email', models.EmailField(max_length=254)),
                ('fecha_de_alta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cocheras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('contacto_telefono', models.IntegerField()),
                ('contacto_email', models.EmailField(max_length=254)),
                ('precio', models.IntegerField()),
                ('fecha_de_alta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('ambientes', models.IntegerField()),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('contacto_telefono', models.IntegerField()),
                ('contacto_email', models.EmailField(max_length=254)),
                ('precio', models.IntegerField()),
                ('fecha_de_alta', models.DateField()),
            ],
        ),
    ]
