# Generated by Django 4.1 on 2022-09-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmo_Coder_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('sub_titulo', models.CharField(max_length=50)),
                ('cuerpo_texto', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog_imagenes')),
            ],
        ),
    ]
