# Generated by Django 4.1 on 2022-09-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmo_Coder_App', '0003_remove_blog_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
