# Generated by Django 4.1 on 2022-09-24 00:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmo_Coder_App', '0006_blog_autor_blog_cuerpo_texto_blog_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cuerpo_texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
