# Generated by Django 4.1 on 2022-09-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmo_Coder_App', '0003_rename_image_avatar_imagen'),
        ('Inmo_Coder_App', '0007_alter_blog_cuerpo_texto'),
    ]

    operations = [
    ]
